services:
  auth-service:
    image: auth-service
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./auth-service:/usr/src/app
    networks:
      - tokoperasi-network
    depends_on:
      - db
    restart: always

  product-service:
    image: product-service
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./product-service:/usr/src/app
    networks:
      - tokoperasi-network
    depends_on:
      - db
    restart: always

  cart-service:
    image: cart-service
    build:
      context: ./cart-service
      dockerfile: Dockerfile
    ports:
      - "6000:6000"
    volumes:
      - ./cart-service:/usr/src/app
    networks:
      - tokoperasi-network
    depends_on:
      - db
    restart: always

  address-service:
    image: address-service
    build:
      context: ./address-service
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    volumes:
      - ./address-service:/usr/src/app
    networks:
      - tokoperasi-network
    depends_on:
      - db
    restart: always

  admin-service:
    image: admin-service
    build:
      context: ./admin-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./admin-service:/usr/src/app
    networks:
      - tokoperasi-network
    depends_on:
      - db
    restart: always

  order-service:
    image: order-service
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./order-service:/usr/src/app
    networks:
      - tokoperasi-network
    depends_on:
      - cart-service
    restart: always
    environment:
      - CART_SERVICE_URL=http://cart-service:6000

  payment-service:
    image: payment-service
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    volumes:
      - ./payment-service:/usr/src/app
    networks:
      - tokoperasi-network
    depends_on:
      - db
    restart: always

  shipping-service:
    image: shipping-service
    build:
      context: ./shipping-service
      dockerfile: Dockerfile
    ports:
      - "11000:11000"
    volumes:
      - ./shipping-service:/usr/src/app
    networks:
      - tokoperasi-network
    depends_on:
      - db
    restart: always

  api-gateway:
    image: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api-gateway:/usr/src/app
    networks:
      - tokoperasi-network
    depends_on:
      - auth-service
      - product-service
      - cart-service
      - order-service
      - payment-service
      - shipping-service
      - admin-service
      - address-service
    restart: always
    environment:
      - AUTH_SERVICE_URL=http://auth-service:4000
      - PRODUCT_SERVICE_URL=http://product-service:5000
      - ORDER_SERVICE_URL=http://order-service:9000
      - CART_SERVICE_URL=http://cart-service:6000
      - PAYMENT_SERVICE_URL=http://payment-service:10000
      - SHIPPING_SERVICE_URL=http://shipping-service:11000
      - ADMIN_SERVICE_URL=http://admin-service:8000
      - ADDRESS_SERVICE_URL=http://address-service:7000

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tokoperasi
    ports:
      - "3306:3306"
    restart: always
    networks:
      - tokoperasi-network

networks:
  tokoperasi-network:
    driver: bridge
